language : 'ru'

toolbar:
  - fontsizeselect | bold italic underline | forecolor backcolor | fontselect | bullist numlist outdent indent | table | alignleft aligncenter alignjustify alignright | undo redo | pastetext pasteword selectall |  uploadimage link image | fullscreen code preview |
   
plugins:
 - uploadimage
 - table 
 - textcolor 
 - colorpicker 