language : 'ru'

toolbar:
  - fontsizeselect | bold italic underline | | fontselect | bullist numlist outdent indent | table | alignleft aligncenter alignjustify alignright | undo redo | pastetext pasteword selectall |  uploadimage link image | fullscreen code |
   
plugins:
  - advlist
  - image
  - link
  - uploadimage
  - code
  - table
  - fullscreen